﻿apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-api-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: command-api-kubenetes
  template:
    metadata:
      labels:
        app: command-api-kubenetes
    spec:
      containers:
      - name: command-api
        image: tuankhoa2009/command-api:v1
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__ConnectionStrings
          value: "Server=tcp:commanddb.database.windows.net,1433;Initial Catalog=DistributedSystemDatabase;Persist Security Info=False;User ID=tuankhoa2009;Password=P@ssword;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"  
        - name: ConnectionStrings__Redis
          value: "redis-13012.c53.west-us.azure.redns.redis-cloud.com:13012,password=QC31L8XwNPbjabdvyKvONaXYvT15J4af,abortConnect=False"
        - name: JwtOption__Issuer
          value: "https://command-api.azurewebsites.net"
        - name: JwtOption__Audience
          value: "https://command-api.azurewebsites.net"
        - name: JwtOption__SecretKey
          value: "oEZqUKrrKDKP7A9OtrB4GfPGJ92vLDpK"
        - name: JwtOption__ExpireMin
          value: "5"
        - name: MasstransitConfiguration__Host
          value: "amqps://wddwqrcb:6SgxhRFiJWQ5WEJL37lvF9UFcFJEl-nX@gerbil.rmq.cloudamqp.com/wddwqrcb"
        - name: MasstransitConfiguration__VHost
          value: "/"
        - name: MasstransitConfiguration__Port
          value: "5672"
        - name: MasstransitConfiguration__UserName
          value: "wddwqrcb"
        - name: MasstransitConfiguration__Password
          value: "6SgxhRFiJWQ5WEJL37lvF9UFcFJEl-nX"
        - name: MessageBusOptions__retryLimit
          value: "3"
        - name: MessageBusOptions__initialInterval
          value: "00:00:05"
        - name: MessageBusOptions__intervalIncrement
          value: "00:00:10"
---
apiVersion: v1
kind: Service
metadata:
  name: command-api-service
spec:
  type: LoadBalancer  
  selector:
    app: command-api-kubenetes
  ports:
    - port: 80
      targetPort: 80
