apiVersion : apps/v1
kind: Deployment
metadata:
  name: tuankhoa2009commandapiv1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuankhoa2009commandapiv1
  template:
    metadata:
      labels:
        app: tuankhoa2009commandapiv1 
    spec:
      containers:
        - name: tuankhoa2009commandapiv1 
          image: distributedk8s.azurecr.io/tuankhoa2009commandapiv1
          ports:
          - containerPort: 80